### ISSUE TITLE
Is there a liscense on these examples?

### ISSUE THREAD

**Issue by JackFly26** [MattCheely/elm-port-examples#6]
I want to use the websocket example on my code, and I just want to make sure that that is allowed. Do I need to give credit or something?

**Comment by MattCheely** [comment]
The websocket example is licensed under the Apache 2.0 license, you are free to use it. I should add license files - thanks for pointing out my oversight!

**Comment by JackFly26** [comment]
Thanks! I'll give you credit in the README anyway.
